python train_ddpm.py --dim 128 \
                    --attn-resolutions "16," \
                    --n-residual 2 \
                    --dim-mults "1,1,2,2,4,4" \
                    --dropout 0 \
                    --n-heads 1 \
                    --beta1 1e-4 \
                    --beta2 0.02 \
                    --n-timesteps 1000 \
                    --fp16 True \
                    --use-ema True \
                    --ema-decay 0.9999 \
                    --batch-size 8 \
                    --epochs 2000 \
                    --device gpu:0,1,2,3 \
                    --lr 2e-5 \
                    --flip False \
                    --results-dir /data/kushagrap20/ddpm_128 \
                    --image-size 128 \
                    --workers 8 \
                    --seed 0 \
                    --dataset 'recons' \
                    --use-cond True \
                    /data/kushagrap20/vaedm/reconstructions/